export default [
    { name: "Havoc", img:"Havoc_Icon.png"},
    { name: "Flatline", img:"Flatline_Icon.png"},
    { name: "G7 Scout", img:"G7_Scout_Icon.png"},
    { name: "Hemlok", img:"Hemlok_Icon.png"},
    { name: "R-301", img:"R-301_Icon.png"},
    { name: "30-30 Repeater", img:"30-30_Repeater_Icon.png"},
    { name: "Alternator", img:"Alternator_Icon.png"},
    { name: "R-99", img:"R-99_Icon.png"},
    { name: "Volt", img:"Volt_Icon.png"},
    { name: "Devotion", img:"Devotion_Icon.png"},
    { name: "Sptifire", img:"Spitfire_Icon.png"},
    { name: "L-STAR", img:"L-Star_Icon.png"},
    { name: "Charge Rifle", img:"Charge_Rifle_Icon.png"},
    { name: "Longbow", img:"Longbow_Icon.png"},
    { name: "Sentinel", img:"Sentinel_Icon.png"},
    { name: "TripleTake", img:"Triple_Take_Icon.png"},
    { name: "EVA-8", img:"Eva-8_Icon.png"},
    { name: "Mastiff", img:"Mastiff_Icon.png"},
    { name: "Mozambique", img:"Mozambique_Icon.png"},
    { name: "RE-45", img:"Re-45_Icon.png"},
    { name: "P2020", img:"P2020_Icon.png"},
    { name: "Wingman", img:"Wingman_Icon.png"},
]