export default [
    { name: "Havoc"},
    { name: "Flatline"},
    { name: "G7 Scout"},
    { name: "Hemlock"},
    { name: "R-301"},
    { name: "30-30 Repeater"},
    { name: "Alternator"},
    { name: "R-99"},
    { name: "Volt"},
    { name: "Devotion"},
    { name: "Sptifire"},
    { name: "L-STAR"},
    { name: "Charge Rifle"},
    { name: "Longbow"},
    { name: "Sentinel"},
    { name: "TripleTake"},
    { name: "EVA-8"},
    { name: "Mastiff"},
    { name: "Mozambique"},
    { name: "RE-45"},
    { name: "P2020"},
    { name: "Wingman"},
]